Feature - Assign roles to users
Code-Hills/codehills-be pull request #14
Opened 2023-03-03 07:22 UTC by Patricknshimiyimana

#### What does this PR do?
> - This PR allows the admin to assign roles to other users

#### How should this be manually tested?
> - Clone this repository
> - checkout to this branch `ft-assign-roles`
> - install the dependencies `npm install` and 
> - Run migrations `npm run db:migrate` 
> - Create some users or run seeds `npm run db:seed` and then start the server `npm run dev`
> - Go to `http://localhost:$PORT/api/v1/docs` in your browser to access the api documentation
> - Login as an admin and try to assign another role to the user in the database

2023-03-05 18:56 UTC, Nkbtemmy requested changes

2023-03-05 18:56 UTC, Nkbtemmy commented on src/database/migrations/uupdate-user-roles.js
> +    await queryInterface.createTable("tbl_users", {
Man, why did you create second migration having the same table names?; please you may delete one and remain with only updated migration. and remember to check the migration file name

2023-03-05 18:56 UTC, Nkbtemmy commented on src/app.js
>      force: false,
We agreed to put here `force:true` instead of commenting `alert`

2023-03-06 11:36 UTC, Nkbtemmy approved these changes

2023-03-06 11:37 UTC, Nkbtemmy approved these changes

2023-03-06 12:46 UTC, alaintresor approved these changes

2023-03-07 07:08 UTC, merged