Fix - Delete referenced project
Code-Hills/codehills-be pull request #28
Opened 2023-06-08 07:47 UTC by Patricknshimiyimana

# What does this PR do?
- this PR fixes the issue of deleting referenced projects
# Description of Task to be completed?
- Before deleting the project delete all userProject records that references it

## Requirements

- [ ] Require dependences installation
- [ ] Require .env update
- [ ] Documentation updated

# How should this be manually tested?
> - Clone this repository
> - checkout to this branch `fix-delete-project`
> - install the dependencies `npm install` and 
> - Run migrations `npm run db:migrate` 
> - Create some users or run seeds `npm run db:seed` and then start the server `npm run dev`
> - Go to `http://localhost:$PORT/api/v1/docs` in your browser to access the api documentation
# Any background context you want to provide?

# What are the relevant pivotal tracker stories?

# Screenshots (if appropriate)

# Questions:
- N/A

2023-06-09 16:43 UTC, nicele08 approved these changes
@Patricknshimiyimana Good work. Just check added comments

2023-06-09 16:43 UTC, nicele08 commented on src/database/relationships/index.js
> +  });
It is a good practice to add the "as" keyword to provide meaningful aliases for the associations.

Hint: 
```javascript
DB.Project.hasMany(DB.UserProject, {
  onDelete: "CASCADE",
  foreignKey: "projectId",
  as: "userProjects", // Alias for the association
});
```

2023-06-09 16:43 UTC, nicele08 commented on src/database/relationships/index.js
> +  });
Same as here; provide meaningful aliases for the associations.

hint:
```javascript
...
as: "project", // Alias for the association
...
```

2023-06-09 16:43 UTC, nicele08 commented on src/database/relationships/index.js
> +  DB.UserProject.belongsTo(DB.User, { foreignKey: "userId" });
Same as here; provide meaningful aliases for the associations.

2023-06-13 17:20 UTC, Cherubln submitted a review, later dismissed
@Patricknshimiyimana also consider adding the inProgress field on every project model.

2023-06-14 12:31 UTC, Patricknshimiyimana commented
> @Patricknshimiyimana also consider adding the inProgress field on every project model.

And that goes with its related actions too!? Like updating it,...

But I thought we had the project `startDate` and `andDate` to track the inProgress projects

2023-06-14 13:35 UTC, Cherubln commented
> And that goes with its related actions too!? Like updating it,...
> 
> But I thought we had the project `startDate` and `andDate` to track the inProgress projects

Yeah, but if you think about it, we should let user decide if the project is completed. I think we shouldn't decide that for them. we can only show them that their project is overdue based on end date. and let them decide if it's finished. that's what I suggest.

2023-06-15 14:33 UTC, Patricknshimiyimana commented
Added a `status` field which can be `pending/in-progress or completed`
What do you think @Cherubln ???

2023-06-15 15:33 UTC, Cherubln requested changes

2023-06-15 15:33 UTC, Cherubln commented on src/database/migrations/20230307201538-create-project.js
> +        type: Sequelize.ENUM("pending", "in-progress", "completed"),
Thank you @Patricknshimiyimana, but I think only in-progress and completed are enough. unless you think there would be cases where project could be in pending mode.

2023-06-16 07:45 UTC, Patricknshimiyimana commented on src/database/migrations/20230307201538-create-project.js
> +        type: Sequelize.ENUM("pending", "in-progress", "completed"),
If you think about it, all projects that have been just added can't be immediately in-progress or completed!
I think there might be a case where a project is added and it is neither in-progress yet nor completed.

what does others think? @denislohan @Nkbtemmy

2023-06-16 08:07 UTC, Cherubln commented on src/database/migrations/20230307201538-create-project.js
> +        type: Sequelize.ENUM("pending", "in-progress", "completed"),
Nice, @Patricknshimiyimana, it is totally understandable I get it, we need all three options. like when the project start date has not been yet reached it should in pending mode.

2023-06-16 08:09 UTC, Cherubln approved these changes
LGTM

2023-06-19 13:16 UTC, merged